S3_ACCESS_KEY:         AKIAJV6W4IGOAJWQZ7LQ
S3_BUCKET:             mygallerya
S3_SECRET_KEY:         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

EMAIL_LOGIN: 'newactionmailer@gmail.com'
EMAIL_PASSWORD: 'new_action_mailer'